[package]
name = "asteroids"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = { version = "0.4.14" }

[dev-dependencies]
tempfile = "3.6"

[profile.dev.package.'*']
opt-level = 3

[profile.release]
lto = true
